GET http://localhost:8080/api/v1/servicios/preguntas-frecuentes
###
GET http://localhost:8080/api/v1/servicios/preguntas-frecuentes/categorias
###

PATCH http://localhost:8080/api/v1/servicios/preguntas-frecuentes/active/2
Content-Type: application/json

{
    "estado": true
}
###

POST http://localhost:8080/api/v1/servicios/preguntas-frecuentes
Content-Type: application/json

{
    "pregunta" : "nose que preguntar",
    "respuesta" : "No se que contestar",
    "categoria" : {
        "id" : 2
    }
}
